# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jakub/Pulpit/Brzydal/Brzydal

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jakub/Pulpit/Brzydal/Brzydal

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jakub/Pulpit/Brzydal/Brzydal/CMakeFiles /home/jakub/Pulpit/Brzydal/Brzydal/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jakub/Pulpit/Brzydal/Brzydal/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Brzydal

# Build rule for target.
Brzydal: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Brzydal
.PHONY : Brzydal

# fast build rule for target.
Brzydal/fast:
	$(MAKE) -f CMakeFiles/Brzydal.dir/build.make CMakeFiles/Brzydal.dir/build
.PHONY : Brzydal/fast

src/face.o: src/face.cpp.o
.PHONY : src/face.o

# target to build an object file
src/face.cpp.o:
	$(MAKE) -f CMakeFiles/Brzydal.dir/build.make CMakeFiles/Brzydal.dir/src/face.cpp.o
.PHONY : src/face.cpp.o

src/face.i: src/face.cpp.i
.PHONY : src/face.i

# target to preprocess a source file
src/face.cpp.i:
	$(MAKE) -f CMakeFiles/Brzydal.dir/build.make CMakeFiles/Brzydal.dir/src/face.cpp.i
.PHONY : src/face.cpp.i

src/face.s: src/face.cpp.s
.PHONY : src/face.s

# target to generate assembly for a file
src/face.cpp.s:
	$(MAKE) -f CMakeFiles/Brzydal.dir/build.make CMakeFiles/Brzydal.dir/src/face.cpp.s
.PHONY : src/face.cpp.s

src/halFace.o: src/halFace.cpp.o
.PHONY : src/halFace.o

# target to build an object file
src/halFace.cpp.o:
	$(MAKE) -f CMakeFiles/Brzydal.dir/build.make CMakeFiles/Brzydal.dir/src/halFace.cpp.o
.PHONY : src/halFace.cpp.o

src/halFace.i: src/halFace.cpp.i
.PHONY : src/halFace.i

# target to preprocess a source file
src/halFace.cpp.i:
	$(MAKE) -f CMakeFiles/Brzydal.dir/build.make CMakeFiles/Brzydal.dir/src/halFace.cpp.i
.PHONY : src/halFace.cpp.i

src/halFace.s: src/halFace.cpp.s
.PHONY : src/halFace.s

# target to generate assembly for a file
src/halFace.cpp.s:
	$(MAKE) -f CMakeFiles/Brzydal.dir/build.make CMakeFiles/Brzydal.dir/src/halFace.cpp.s
.PHONY : src/halFace.cpp.s

src/imageFace.o: src/imageFace.cpp.o
.PHONY : src/imageFace.o

# target to build an object file
src/imageFace.cpp.o:
	$(MAKE) -f CMakeFiles/Brzydal.dir/build.make CMakeFiles/Brzydal.dir/src/imageFace.cpp.o
.PHONY : src/imageFace.cpp.o

src/imageFace.i: src/imageFace.cpp.i
.PHONY : src/imageFace.i

# target to preprocess a source file
src/imageFace.cpp.i:
	$(MAKE) -f CMakeFiles/Brzydal.dir/build.make CMakeFiles/Brzydal.dir/src/imageFace.cpp.i
.PHONY : src/imageFace.cpp.i

src/imageFace.s: src/imageFace.cpp.s
.PHONY : src/imageFace.s

# target to generate assembly for a file
src/imageFace.cpp.s:
	$(MAKE) -f CMakeFiles/Brzydal.dir/build.make CMakeFiles/Brzydal.dir/src/imageFace.cpp.s
.PHONY : src/imageFace.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/Brzydal.dir/build.make CMakeFiles/Brzydal.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/Brzydal.dir/build.make CMakeFiles/Brzydal.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/Brzydal.dir/build.make CMakeFiles/Brzydal.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/servo.o: src/servo.cpp.o
.PHONY : src/servo.o

# target to build an object file
src/servo.cpp.o:
	$(MAKE) -f CMakeFiles/Brzydal.dir/build.make CMakeFiles/Brzydal.dir/src/servo.cpp.o
.PHONY : src/servo.cpp.o

src/servo.i: src/servo.cpp.i
.PHONY : src/servo.i

# target to preprocess a source file
src/servo.cpp.i:
	$(MAKE) -f CMakeFiles/Brzydal.dir/build.make CMakeFiles/Brzydal.dir/src/servo.cpp.i
.PHONY : src/servo.cpp.i

src/servo.s: src/servo.cpp.s
.PHONY : src/servo.s

# target to generate assembly for a file
src/servo.cpp.s:
	$(MAKE) -f CMakeFiles/Brzydal.dir/build.make CMakeFiles/Brzydal.dir/src/servo.cpp.s
.PHONY : src/servo.cpp.s

src/simpleFace.o: src/simpleFace.cpp.o
.PHONY : src/simpleFace.o

# target to build an object file
src/simpleFace.cpp.o:
	$(MAKE) -f CMakeFiles/Brzydal.dir/build.make CMakeFiles/Brzydal.dir/src/simpleFace.cpp.o
.PHONY : src/simpleFace.cpp.o

src/simpleFace.i: src/simpleFace.cpp.i
.PHONY : src/simpleFace.i

# target to preprocess a source file
src/simpleFace.cpp.i:
	$(MAKE) -f CMakeFiles/Brzydal.dir/build.make CMakeFiles/Brzydal.dir/src/simpleFace.cpp.i
.PHONY : src/simpleFace.cpp.i

src/simpleFace.s: src/simpleFace.cpp.s
.PHONY : src/simpleFace.s

# target to generate assembly for a file
src/simpleFace.cpp.s:
	$(MAKE) -f CMakeFiles/Brzydal.dir/build.make CMakeFiles/Brzydal.dir/src/simpleFace.cpp.s
.PHONY : src/simpleFace.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... Brzydal"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... src/face.o"
	@echo "... src/face.i"
	@echo "... src/face.s"
	@echo "... src/halFace.o"
	@echo "... src/halFace.i"
	@echo "... src/halFace.s"
	@echo "... src/imageFace.o"
	@echo "... src/imageFace.i"
	@echo "... src/imageFace.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/servo.o"
	@echo "... src/servo.i"
	@echo "... src/servo.s"
	@echo "... src/simpleFace.o"
	@echo "... src/simpleFace.i"
	@echo "... src/simpleFace.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

